### ISSUE TITLE
AttributeError when running 

### ISSUE THREAD

**Issue by zimsekdanilo** [ninlith/audio-visualizer-screenlet#2]
I installed all dependecies. Program starts but fallowing error appers. Am I missing something? 

`python3 avs.py 

2017-02-06 14:12:07 INFO auxiliary.conf - Config path: /home/danilo/.config/audio-visualizer-screenlet
Traceback (most recent call last):
  File "avs.py", line 90, in <module>
    main()
  File "avs.py", line 51, in main
    rate=recorder.rate,
  File "/home/danilo/Prejemi/audio-visualizer-screenlet/avs/process/audio_processor.py", line 43, in __init__
    a = pyfftw.empty_aligned(
AttributeError: 'module' object has no attribute 'empty_aligned'
`

**Comment by ninlith** [comment]
Too old pyFFTW? The package appears to be missing from Debian testing/unstable currently. Try replacing empty_aligned with n_byte_align_empty.
